const CHANGE_LOCATION = 'CHANGE_LOCATION'

const GET_SUGGESTIONS = 'GET_SUGGESTIONS'
const GET_SUGGESTIONS_SUCCESS = GET_SUGGESTIONS + '_SUCCESS'
const GET_SUGGESTIONS_FAIL = GET_SUGGESTIONS + '_FAIL'

const CHANGE_SUGGESTIONS = 'CHANGE_SUGGESTIONS'

const GET_LOCATION_DATA = 'GET_LOCATION_DATA'
const GET_LOCATION_DATA_SUCCESS = GET_LOCATION_DATA + '_SUCCESS'
const GET_LOCATION_DATA_FAIL = GET_LOCATION_DATA + '_FAIL'

const GET_FORECAST = 'GET_FORECAST'
const GET_FORECAST_SUCCESS = GET_FORECAST + '_SUCCESS'
const GET_FORECAST_FAIL = GET_FORECAST + '_FAIL'

const CHANGE_FORECAST = 'CHANGE_FORECAST'

export {
  GET_LOCATION_DATA,
  GET_LOCATION_DATA_SUCCESS,
  GET_LOCATION_DATA_FAIL,
  CHANGE_LOCATION,
  GET_SUGGESTIONS,
  GET_SUGGESTIONS_SUCCESS,
  GET_SUGGESTIONS_FAIL,
  GET_FORECAST,
  GET_FORECAST_FAIL,
  GET_FORECAST_SUCCESS,
  CHANGE_FORECAST,
  CHANGE_SUGGESTIONS
}
